services:
  - type: web
    name: quitter-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT -w 1 app:server
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RECAPTCHA_SITE_KEY
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: DEBUG
        value: "false"
      - key: ENABLE_STATE_WORKER
        value: "true"
      - key: DISABLE_RECAPTCHA
        value: "false"
